- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 368089c3-630d-471e-922b-0191dc69ed73
  loglevel: INFO
  name: 004 - Cconfigure Ethernet1-2 ios4
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ios4
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        commandsList: |2-
          term len 0
          term mon
          enable
          satec
          conf t
          int ethernet1/2
          ip address 30.1.4.1 255.255.255.0
          end
          wr

      description: 004 - Cconfigure Ethernet1-2 ios4
      nodeStep: true
      type: ssh-node-step-executor
    keepgoing: false
    strategy: node-first
  uuid: 368089c3-630d-471e-922b-0191dc69ed73
