jobs:
    - name: get ios1 device configuration
      filter: ios1
      commandsList: "show running"
      regex: true
      regex_negate: false
      regex_expr: .*(Current configuration).*
      vendor: ios
      enable: satec
    - name: load ios1 preconfiguration
      filter: ios1
      commandsList: |
          conf t
          !-- configuraci贸n de interfaz de loopback
          interface Loopback0
           ip address 10.1.0.1 255.255.255.255
           ip ospf 1 area 0
          !
          !-- configuraci贸n de interfaces mpls de core
          interface Ethernet1/0
           ip address 10.1.12.1 255.255.255.0
           ip ospf network point-to-point
           ip ospf 1 area 0
           mpls ip
          !
          interface Ethernet1/1
           ip address 10.1.13.1 255.255.255.0
           ip ospf network point-to-point
           ip ospf 1 area 0
           mpls ip
          !
          !-- configuraci贸n de IGP
          router ospf 1
           passive-interface default
           no passive-interface Ethernet1/0
           no passive-interface Ethernet1/1
          !
          !-- configuraci贸n de BGP
          router bgp 65001
           bgp router-id 10.1.0.1
           bgp log-neighbor-changes
           no bgp default ipv4-unicast
           neighbor CLIENTE peer-group
           neighbor CLIENTE remote-as 65002
           neighbor IBGP peer-group
           neighbor IBGP remote-as 65001
           neighbor IBGP password 7 0518071B244F
           neighbor IBGP update-source Loopback0
           neighbor 10.1.0.2 peer-group IBGP
           neighbor 10.1.0.3 peer-group IBGP
          !
           address-family ipv4
            neighbor CLIENTE send-community
            neighbor CLIENTE default-originate
            neighbor IBGP send-community
            neighbor IBGP next-hop-self
            neighbor 10.1.0.2 activate
            neighbor 10.1.0.3 activate
           exit-address-family
           !
           address-family vpnv4
            neighbor IBGP send-community both
            neighbor 10.1.0.2 activate
            neighbor 10.1.0.3 activate
           exit-address-family
           !
          !
          end
          wr
      regex: true
      regex_negate: true
      regex_expr: .*(% In).*
      vendor: ios
    - name: get ios1 device configuration
      filter: ios1
      commandsList: "show running"
      regex: true
      regex_negate: false
      regex_expr: .*(Current configuration).*
      vendor: ios
    - name: standard protocols check (ospf|ldp|bgp)
      filter: ios1
      commandsList: |
          show ip ospf neighbor
          show mpls ldp neighbor
          show bgp all summary
      regex: false
      regex_negate: false
      regex_expr: .*(Current configuration)
      vendor: ios

    - name: verify current ios2 interface configuration
      filter: ios2
      commandsList: |
          show interface Ethernet1/0
          show run interface Ethernet1/0      
      regex: false
      regex_negate: false
      regex_expr: .*(Current configuration)
      vendor: ios



    - name: configure ios2 link
      filter: ios2
      commandsList: |
          conf t
          interface Ethernet1/0
           no shut
           ip address 10.1.12.2 255.255.255.0
          !
          end
          wr      
      regex: true
      regex_negate: true
      regex_expr: .*(% In).*
      vendor: ios

    - name: Verify ios2 - ios1 local connectivity
      filter: ios2
      commandsList: |
        show run interface e1/0
        show interface ethernet1/0
        ping 10.1.12.1    

      regex: true
      regex_negate: true
      regex_expr: .*percent is 0 .*
      vendor: ios


    - name: configure OSPF in ios2 - ios1 link
      filter: ios2
      commandsList: |
        conf t
        interface Ethernet1/0
         ip ospf network point-to-point
         ip ospf 1 area 0
        !
        router ospf 1
         no passive-interface Ethernet1/0
        !
        end
        wr     
      regex: true
      regex_negate: true
      regex_expr: .*(% In).*
      vendor: ios



    - name: Verify OSPF in ios2 - ios1 link
      filter: ios2
      commandsList: |
        show ip ospf neighbor
        show ip route 10.1.0.1   
      regex: true
      regex_negate: False
      regex_expr: .*10\.1\.0\.1 +0 +(FULL).*10.1.12.1.*from 10.1.0.1.*
      vendor: ios



    - name: configure LDP in ios2 - ios1 link
      filter: ios2
      commandsList: |
        conf t
        interface Ethernet1/0
         mpls ip
        !
        end
        wr  
      regex: true
      regex_negate: true
      regex_expr: .*(% In).*
      vendor: ios



    - name: Verify LDP in ios2 - ios1 link
      filter: ios2
      commandsList: |
        show mpls ldp neighbor  
      regex: true
      regex_negate: False
      regex_expr: ".*Peer LDP Ident: (10.1.0.1).*"
      vendor: ios


    - name: configure BGP session in ios2 against ios1
      filter: ios2
      commandsList: |
        conf t

        router bgp 65001
        neighbor 10.1.0.1 peer-group RR-CLIENT
        !
        address-family ipv4
         neighbor 10.1.0.1 activate
        exit-address-family
        !
        address-family vpnv4
         neighbor 10.1.0.1 activate
        exit-address-family
        !        
        end
        wr
      regex: true
      regex_negate: true
      regex_expr: .*(% In).*
      vendor: ios



    - name: Verify ios2 - ios1 BGP session
      filter: ios2
      commandsList: |
        show bgp all
        show ip bgp neighbor 10.1.0.1
        show bgp all summary | i 10.1.0.1
      regex: true
      regex_negate: False
      regex_expr: ".*BGP state = (Established).*"
      vendor: ios






    - name: Verify vqfx3 current interface configuration
      filter: vqfx3
      commandsList: |
        show configuration interface em3
      regex: true
      regex_negate: true
      regex_expr: .*(known|syntax)*
      vendor: juniper

    - name: Configure vqfx interface
      filter: vqfx3
      commandsList: |
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        
        
        
        configure
        set interfaces em3 unit 0 family inet address 10.1.13.3/24
        show | compare
        commit and-quit
        
        
        
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        [CTRL+D]
        
        
        
        
        
        show interfaces em3 | no-more
        
        
        
        show configuration interfaces em3 | no-more
      regex: true
      regex_negate: true
      regex_expr: .*(error)*
      vendor: juniper

    - name: Verify ping connectivity between vqfx3 and ios1
      filter: vqfx3
      commandsList: |
        show configuration interface em3
        ping 10.1.13.1 rapid count 5
      regex: true
      regex_negate: false
      regex_expr: ".*(4|5) packets received.*"
      vendor: juniper


    - name: Configure OSPF vqfx interface 
      filter: vqfx3
      commandsList: |
        configure
        set protocols ospf area 0 interface em3.0 interface-type p2p
        show | compare
        commit and-quit
      regex: true
      regex_negate: true
      regex_expr: .*(error)*
      vendor: juniper

    - name: Verify OSPF in vqfx3 - ios1 link
      filter: vqfx3
      commandsList: |
        show ospf neighbor
        show route 10.1.0.1 exact table inet.0
      regex: true
      regex_negate: false
      regex_expr: .*(Full +10.1.0.1).*via em3.0.*
      vendor: juniper




    - name: Configure LDP vqfx interface 
      filter: vqfx3
      commandsList: |
        configure
        set interfaces em3 unit 0 family mpls
        set protocols ldp interface em3.0
        show | compare
        commit and-quit
      regex: true
      regex_negate: true
      regex_expr: .*(error)*
      vendor: juniper

    - name: Verify LDP in vqfx3 - ios1 link
      filter: vqfx3
      commandsList: |
        show ldp neighbor
        show ldp session
        show ldp database session 10.1.0.1
      regex: true
      regex_negate: false
      regex_expr: .*(10.1.0.1 +Operational).*
      vendor: juniper



    - name: configure BGP session in vqfx3 against ios1
      filter: vqfx3
      commandsList: |
        configure
        set protocols bgp group RR-CLIENTS neighbor 10.1.0.1
        show | compare
        commit and-quit
      regex: true
      regex_negate: true
      regex_expr: .*(error)*
      vendor: juniper

    - name: Verify vqfx3 - ios1 BGP session
      filter: vqfx3
      commandsList: |
        show bgp summary | no-more
      regex: true
      regex_negate: False
      regex_expr: .*10.1.0.1 +65001 +\d+ +\d+ +\d+ +\d+ +\d+:\d+:\d+ +(Establ).*
      vendor: juniper



    - name: Verify ios1 is integraged - OSPF
      filter: ios1
      commandsList: |
        show ip ospf neighbor
        show ip ospf database
      regex: true
      regex_negate: false
      regex_expr: .*(10.1.0.3.*FULL.*10.1.0.2.*FULL).*
      vendor: ios


    - name: Verify ios1 is integraged - LDP
      filter: ios1
      commandsList: |
        show mpls ldp neighbor
        show mpls forwarding
      regex: true
      regex_negate: false
      regex_expr: ".*(Ident: 10.1.0.3.*Ident: 10.1.0.2|Ident: 10.1.0.2.*Ident: 10.1.0.3).*"
      vendor: ios
      


    - name: Verify ios1 is integraged - BGP
      filter: ios1
      commandsList: |
        show bgp all summary
      regex: true
      regex_negate: False
      regex_expr: .*(10.1.0.2.*:\d{2} +\d+.*10.1.0.3.*:\d{2} +\d+.*).*
      vendor: ios

    - name: Verify ios1 is integraged - traceroute against ios4
      filter: ios1
      commandsList: |
        traceroute 10.1.0.4 source 10.1.0.1 probe 1 timeout 1 
      regex: true
      regex_negate: False
      regex_expr: .*MPLS. Label \d+.*(10.1.24.4).*
      vendor: ios











