jobs:
- name: "ios1:ping a la interfaz del CE local"
  filter: ios1
  regex: true
  regex_negate: false
  regex_expr: .*Success rate is (100|50) percent.*
  vendor: ios
  commandsList: |
    !-- ios1:ping a la interfaz del CE local
    ping vrf L3VPN 30.1.1.100
- name: "ios1: comprobación de que la sesión BGP levanta"
  filter: ios1
  regex: true
  regex_negate: False
  regex_expr: .*30.1.1.100 +\d+ +65002 +\d+ +\d+ +\d+ +\d+ +\d+ +\d+:\d+\:\d+ +(\d+).*
  vendor: ios
  commandsList: |
    !-- ios1: comprobación de que la sesión BGP levanta
    show bgp vpnv4 unicast vrf L3VPN summary
- name: "ios1: verificación de que se aprenden prefijos de ce1 via BGP."
  filter: ios1
  regex: true
  regex_negate: true
  regex_expr: .*Network not in (table).*
  vendor: ios
  commandsList: |
    !-- ios1: verificación de que se aprenden prefijos de ce1 via BGP.
    show bgp vpnv4 unicast vrf L3VPN 30.0.0.1
- name: "ios1: verificación de que se aprenden prefijos de ce1 en la tabla de rutas."
  filter: ios1
  regex: true
  regex_negate: true
  regex_expr: .*Network not in (table).*
  vendor: ios
  commandsList: |
    !-- ios1: verificación de que se aprenden prefijos de ce1 en la tabla de rutas.
    show ip route vrf L3VPN 30.0.0.1
