jobs:

- name: " Configuración en ios1 de la L3VPN"
  regex: false
  filter: ios1
  vendor: ios
  commandsList: |
    !-- Configuración en ios1 de la L3VPN
    conf t
    vrf definition L3VPN
     rd 10.1.0.1:1
     !
     address-family ipv4
      route-target export 65001:1
      route-target import 65001:1
     exit-address-family
    !
    interface Ethernet1/3
     no shut
     vrf forwarding L3VPN
     ip address 30.1.1.1 255.255.255.0
    !
    
    router bgp 65001
     address-family ipv4 vrf L3VPN
      redistribute connected
      neighbor 30.1.1.100 remote-as 65002
      neighbor 30.1.1.100 activate
      neighbor 30.1.1.100 as-override
      neighbor 30.1.1.100 timers 5 15
     exit-address-family
     !
    !
    end
    wr

- name: " Configuración en ios2 de la L3VPN"
  regex: false
  filter: ios1
  vendor: ios
  commandsList: |
    !-- Configuración en ios4 de la L3VPN
    conf t
    vrf definition L3VPN
     rd 10.1.0.2:1
     !
     address-family ipv4
      route-target export 65001:1
      route-target import 65001:1
     exit-address-family
    !
    interface Ethernet1/3
     no shut
     vrf forwarding L3VPN
     ip address 30.1.2.1 255.255.255.0
    !
    
    router bgp 65001
     address-family ipv4 vrf L3VPN
      redistribute connected
      neighbor 30.1.2.100 remote-as 65002
      neighbor 30.1.2.100 activate
      neighbor 30.1.2.100 as-override
      neighbor 30.1.2.100 timers 5 15
     exit-address-family
     !
    !
    end
    wr

- name: " Configuración en ios4 de la L3VPN"
  regex: false
  filter: ios1
  vendor: ios
  commandsList: |
    !-- Configuración en ios4 de la L3VPN
    conf t
    vrf definition L3VPN
     rd 10.1.0.4:1
     !
     address-family ipv4
      route-target export 65001:1
      route-target import 65001:1
     exit-address-family
    !
    interface Ethernet1/2
     no shut
     vrf forwarding L3VPN
     ip address 30.1.4.1 255.255.255.0
    !
    
    router bgp 65001
     address-family ipv4 vrf L3VPN
      redistribute connected
      neighbor 30.1.4.100 remote-as 65002
      neighbor 30.1.4.100 activate
      neighbor 30.1.4.100 as-override
      neighbor 30.1.4.100 timers 5 15
     exit-address-family
     !
    !
    end
    wr

