---
- name: test playbook
  hosts: all
  gather_facts: no
  vars:
    ansible_user: antidote
    ansible_password: antidotepassword
  tasks:

    - name: Debug date
      shell: date
      register: date_output

    - debug:
        msg: "{{ date_output }}"