- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 368089c3-630d-471e-922b-0191dc69ed42
  loglevel: INFO
  name: 001 - Configure ios1
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ios1
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        commandsList: |2-
          conf t
          !-- configuraci贸n de interfaz de loopback
          interface Loopback0
          ip address 10.1.0.1 255.255.255.255
          ip ospf 1 area 0
          !
          !-- configuraci贸n de interfaces mpls de core
          interface Ethernet1/0
          ip address 10.1.12.1 255.255.255.0
          ip ospf network point-to-point
          ip ospf 1 area 0
          mpls ip
          !
          interface Ethernet1/1
          ip address 10.1.13.1 255.255.255.0
          ip ospf network point-to-point
          ip ospf 1 area 0
          mpls ip
          !
          !-- configuraci贸n de IGP
          router ospf 1
          passive-interface default
          no passive-interface Ethernet1/0
          no passive-interface Ethernet1/1
          !
          !-- configuraci贸n de BGP
          router bgp 65001
          bgp router-id 10.1.0.1
          bgp log-neighbor-changes
          no bgp default ipv4-unicast
          neighbor CLIENTE peer-group
          neighbor CLIENTE remote-as 65002
          neighbor IBGP peer-group
          neighbor IBGP remote-as 65001
          neighbor IBGP password 7 0518071B244F
          neighbor IBGP update-source Loopback0
          neighbor 10.1.0.2 peer-group IBGP
          neighbor 10.1.0.3 peer-group IBGP
          !
          address-family ipv4
            neighbor CLIENTE send-community
            neighbor CLIENTE default-originate
            neighbor IBGP send-community
            neighbor IBGP next-hop-self
            neighbor 20.1.1.100 activate
            neighbor 10.1.0.2 activate
            neighbor 10.1.0.3 activate
          exit-address-family
          !
          address-family vpnv4
            neighbor IBGP send-community both
            neighbor 10.1.0.2 activate
            neighbor 10.1.0.3 activate
          exit-address-family
          !
          !
          end
          wr
      description: 002 - Get running config
      nodeStep: true
      type: ssh-node-step-executor
    keepgoing: false
    strategy: node-first
  uuid: 368089c3-630d-471e-922b-0191dc69ed42
