- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 368089c3-630d-471e-922b-0191dc69ed50
  loglevel: INFO
  name: 010 - Configurate protocol IGP ios2
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ios2
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        commandsList: |2-
          enable
          satec
          term len 0
          conf t
          interface Ethernet1/0
           ip ospf network point-to-point
           ip ospf 1 area 0
          !
          router ospf 1
           no passive-interface Ethernet1/0
          !
          end
          wr
      description: 010 - Configurate protocol IGP ios2
      nodeStep: true
      type: ssh-node-step-executor
    keepgoing: false
    strategy: node-first
  uuid: 368089c3-630d-471e-922b-0191dc69ed50
