- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 368089c3-630d-471e-922b-0191dc69ed52
  loglevel: INFO
  name: 012 - Configurate protocol IGP vqfx3
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: vqfx3
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        commandsList: |2-
          [CTRL-C]
          configure
          set protocols ospf area 0.0.0.0 interface em3.0 interface-type p2p
          show | compare
          commit and-quit
      description: 012 - Configurate protocol IGP vqfx3
      nodeStep: true
      type: ssh-node-step-executor
    keepgoing: false
    strategy: node-first
  uuid: 368089c3-630d-471e-922b-0191dc69ed52
