- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 368089c3-630d-471e-922b-0191dc69ed58
  loglevel: INFO
  name: 018 - Configurate protocol BGP ios2
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ios2
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        commandsList: |2-
          enable
          satec
          term len 0
          conf t
          router bgp 65001
          neighbor 10.1.0.1 peer-group RR-CLIENT
          !
          address-family ipv4
          neighbor 10.1.0.1 activate
          exit-address-family
          !
          address-family vpnv4
          neighbor 10.1.0.1 activate
          exit-address-family
          !
          !
          end
          wr
      description: 018 - Configurate protocol BGP ios2
      nodeStep: true
      type: ssh-node-step-executor
    keepgoing: false
    strategy: node-first
  uuid: 368089c3-630d-471e-922b-0191dc69ed58
