---
lessonName: Taller automatizacion con Rundeck
lessonId: 66
category: fundamentals
lessonDiagram: https://cdn1.imggmi.com/uploads/2019/9/19/53d489bb95e6b5b2acb9b8f039220a5b-full.png
tier: prod
prereqs:
  - 14  # YAML
  - 23  # Linux
description: Laboratorio para probar como realizar configuraciones y troubleshooting en redes multivendor
slug: rundeck
tags:
- rundeck
- testing
collection: 1

endpoints:
#- name: linux1
#  image: antidotelabs/utility
#  presentations:
#  - name: cli
#    port: 22
#    type: ssh

- name: vqfx3
  image: antidotelabs/vqfx-snap1
  configurationType: napalm-junos
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: ios1
  image: satecdev/vrouter
  configurationType: ansible
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: ios2
  image: satecdev/vrouter
  configurationType: ansible
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: ios4
  image: satecdev/vrouter
  configurationType: ansible
  presentations:
  - name: cli
    port: 22
    type: ssh
  additionalPorts: [22]

- name: vhost
  image: satecdev/vrouter
  configurationType: ansible
#  presentations:
#  - name: cli
#    port: 22
#    type: ssh
  additionalPorts: [22]

- name: rundeck
  image: satecdev/rundeck
  presentations:
  - name: cli
    port: 22
    type: ssh
  - name: web
    port: 80
    type: http

connections:
- a: ios1
  b: ios2
- a: ios1
  b: vqfx3
- a: ios2
  b: vqfx3
- a: ios1
  b: vhost
- a: ios1
  b: vhost
- a: ios2
  b: vhost
- a: ios2
  b: vhost
- a: vqfx3
  b: vhost
- a: vqfx3
  b: vhost
- a: ios4
  b: ios2
- a: ios4
  b: vhost
- a: ios4
  b: vhost



stages:
  - id: 1
    description: Provision de PE
  - id: 2
    description: Provisión de servicio L3VPN
  - id: 3
    description: Troubleshooting - Ticket 01
  - id: 4
    description: Troubleshooting - Ticket 02
  - id: 5
    description: Troubleshooting - Ticket 03




