- name: Carga configuraciones
  hosts: all
  vars:
    ansible_user: antidote
    ansible_password: antidotepassword
  gather_facts: no
  tasks:
  - name: Copy project jar
    copy:
      src: stage1-20190920-121200.rdproject.jar
      dest: /projects/
      owner: antidote
      group: antidote
      mode: '0644'
  - name: Copy inventory file 
    copy:
      src: rundeckinventory
      dest: /projects/
      owner: antidote
      group: antidote
      mode: '0644'
  - name: Copy password file
    copy:
      src: password
      dest: /projects/
      owner: antidote
      group: antidote
      mode: '0644'
  - name: Delete project
    shell: rd projects delete -p stage1 -y
  - name: Create project
    shell: rd projects create -p stage1
  - name: Load keys
    shell: "rd keys create -t password -p /antidote/cpe -f /projects/password"
  - name: Import nodes 
    shell: |
      curl -vvv -X POST -H "Content-Type: application/json" -d '{ "name": "stage1", "config": { "project.label":"stage1", "resources.source.2.type":"file", "resources.source.2.config.file":"/projects/rundeckinventory.json", "resources.source.2.config.format":"resourcejson" } }' --cookie /antidote/stage1/configs/rd_cookie "http://localhost:4440/${SYRINGE_FULL_REF}/api/32/projects"
  - name: Load project
    shell: |
      rd projects archives import -p "stage1" --file /projects/stage1-20190920-121200.rdproject.jar
