- name: Carga configuraciones
  hosts: all
  vars:
    ansible_user: antidote
    ansible_password: antidotepassword
  gather_facts: no
  tasks:
  - name: test echo
    command: echo hola > /antidote/stage1/configs/blabla
  - name: Get cookie
    command: 'curl   -D -   -X POST   -H "Content-Type: application/x-www-form-urlencoded"   -H "Cache-Control: no-cache"   -d "j_username=admin&j_password=admin"   --cookie-jar /antidote/stage1/configs/rd_cookie   http://localhost:4440/${SYRINGE_FULL_REF}/j_security_check'
  - name: Create SATEC
    command: 'curl -vvv -X POST -H "Content-Type: application/json" -d '{ "name": "SATEC", "config": { "project.label":"stage1-label" } }' --cookie /antidote/stage1/configs/rd_cookie "http://localhost:4440/${SYRINGE_FULL_REF}/api/32/projects"'
  - name: Create jobs
    command: 'curl -vvv -X POST -H "Content-Type: application/yaml" --data-binary @/antidote/stage1/configs/rundeck.jobs.yml --cookie /antidote/stage1/configs/rd_cookie "http://localhost:4440/${SYRINGE_FULL_REF}/api/32/project/SATEC/jobs/import?fileformat=yaml&dupeOption=update"'

