- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 35be6d57-a892-49be-81ee-32e599ebf30a
  loglevel: INFO
  name: '[000] get ios1 device configuration'
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ios1
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        commandsList: 'enable

          satec

          term len 0

          show running'
      description: job_name
      nodeStep: true
      plugins:
        LogFilter:
        - config:
            hideOutput: false
            logData: true
            name: result
            regex: .*(Current configuration).*
          type: key-value-data-multilines
      type: ssh-node-step-executor
    - configuration:
        command: '[ ! -z "${data.result}" ]'
      nodeStep: true
      type: localexec
    keepgoing: true
    strategy: node-first
  uuid: 35be6d57-a892-49be-81ee-32e599ebf30a
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 009dcfe7-357e-442e-a64b-2a680f3735f6
  loglevel: INFO
  name: '[001] load ios1 preconfiguration'
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ios1
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        commandsList: "enable\nsatec\nterm len 0\nconf t\n!-- configuraci\xF3n de\
          \ interfaz de loopback\ninterface Loopback0\n ip address 10.1.0.1 255.255.255.255\n\
          \ ip ospf 1 area 0\n!\n!-- configuraci\xF3n de interfaces mpls de core\n\
          interface Ethernet1/0\n ip address 10.1.12.1 255.255.255.0\n ip ospf network\
          \ point-to-point\n ip ospf 1 area 0\n mpls ip\n!\ninterface Ethernet1/1\n\
          \ ip address 10.1.13.1 255.255.255.0\n ip ospf network point-to-point\n\
          \ ip ospf 1 area 0\n mpls ip\n!\n!-- configuraci\xF3n de IGP\nrouter ospf\
          \ 1\n passive-interface default\n no passive-interface Ethernet1/0\n no\
          \ passive-interface Ethernet1/1\n!\n!-- configuraci\xF3n de BGP\nrouter\
          \ bgp 65001\n bgp router-id 10.1.0.1\n bgp log-neighbor-changes\n no bgp\
          \ default ipv4-unicast\n neighbor CLIENTE peer-group\n neighbor CLIENTE\
          \ remote-as 65002\n neighbor IBGP peer-group\n neighbor IBGP remote-as 65001\n\
          \ neighbor IBGP password 7 0518071B244F\n neighbor IBGP update-source Loopback0\n\
          \ neighbor 10.1.0.2 peer-group IBGP\n neighbor 10.1.0.3 peer-group IBGP\n\
          !\n address-family ipv4\n  neighbor CLIENTE send-community\n  neighbor CLIENTE\
          \ default-originate\n  neighbor IBGP send-community\n  neighbor IBGP next-hop-self\n\
          \  neighbor 10.1.0.2 activate\n  neighbor 10.1.0.3 activate\n exit-address-family\n\
          \ !\n address-family vpnv4\n  neighbor IBGP send-community both\n  neighbor\
          \ 10.1.0.2 activate\n  neighbor 10.1.0.3 activate\n exit-address-family\n\
          \ !\n!\nend\nwr\n"
      description: job_name
      nodeStep: true
      plugins:
        LogFilter:
        - config:
            hideOutput: false
            logData: true
            name: result
            regex: .*(% In).*
          type: key-value-data-multilines
      type: ssh-node-step-executor
    - configuration:
        command: '[ -z "${data.result}" ]'
      nodeStep: true
      type: localexec
    keepgoing: true
    strategy: node-first
  uuid: 009dcfe7-357e-442e-a64b-2a680f3735f6
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: a96044b2-8a0c-4598-b8bb-1b07b456e49d
  loglevel: INFO
  name: '[002] get ios1 device configuration'
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ios1
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        commandsList: 'enable

          satec

          term len 0

          show running'
      description: job_name
      nodeStep: true
      plugins:
        LogFilter:
        - config:
            hideOutput: false
            logData: true
            name: result
            regex: .*(Current configuration).*
          type: key-value-data-multilines
      type: ssh-node-step-executor
    - configuration:
        command: '[ ! -z "${data.result}" ]'
      nodeStep: true
      type: localexec
    keepgoing: true
    strategy: node-first
  uuid: a96044b2-8a0c-4598-b8bb-1b07b456e49d
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: cbcaa9fb-35f9-40b9-ac0d-88d6a9b3dad3
  loglevel: INFO
  name: '[003] standard protocols check (ospf|ldp|bgp)'
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ios1
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        commandsList: 'enable

          satec

          term len 0

          show ip ospf neighbor

          show mpls ldp neighbor

          show bgp all summary

          '
      description: job_name
      nodeStep: true
      type: ssh-node-step-executor
    keepgoing: true
    strategy: node-first
  uuid: cbcaa9fb-35f9-40b9-ac0d-88d6a9b3dad3
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: efc58ee6-1d60-460c-b74d-87976ac48f52
  loglevel: INFO
  name: '[004] verify current ios2 interface configuration'
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ios2
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        commandsList: "enable\nsatec\nterm len 0\nshow interface Ethernet1/0\nshow\
          \ run interface Ethernet1/0      \n"
      description: job_name
      nodeStep: true
      type: ssh-node-step-executor
    keepgoing: true
    strategy: node-first
  uuid: efc58ee6-1d60-460c-b74d-87976ac48f52
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 6004f70f-c173-48d1-a6c5-02c863cd974f
  loglevel: INFO
  name: '[005] configure ios2 link'
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ios2
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        commandsList: "enable\nsatec\nterm len 0\nconf t\ninterface Ethernet1/0\n\
          \ no shut\n ip address 10.1.12.2 255.255.255.0\n!\nend\nwr      \n"
      description: job_name
      nodeStep: true
      plugins:
        LogFilter:
        - config:
            hideOutput: false
            logData: true
            name: result
            regex: .*(% In).*
          type: key-value-data-multilines
      type: ssh-node-step-executor
    - configuration:
        command: '[ ! -z "${data.result}" ]'
      nodeStep: true
      type: localexec
    keepgoing: true
    strategy: node-first
  uuid: 6004f70f-c173-48d1-a6c5-02c863cd974f
